name: Deploy to AWS S3
on:
  push:
    branches:
      - master
env:
  env_branch: ${GITHUB_REF##*/}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: print name
        run: |
          if [contains(${{env.env_branch}}, master]; then
            echo "true master"
          else
            echo "false branch"
#echo "env branch: " ${{env.env_branch}}
