name: testing if else condition

on:
  push:
    branches:
      - master
      - '**'  # allow all branches for generality, optional

env:
  env_branch: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set branch_folder based on branch
        id: vars
        run: |
          echo "Current branch is: $env_branch"
          if [[ "$env_branch" == *"master"* ]]; then
            echo "branch_folder=master-folder" >> $GITHUB_ENV
          else
            echo "branch_folder=dev-folder" >> $GITHUB_ENV
          fi
      - name: Use branch_folder variable
        run: |
          echo "Branch folder is: $branch_folder"
