name: testing if else condition

on:
  push:
    branches:
      - master
      - '**'  # allow all branches for generality, optional

env:
  env_branch: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Print branch and conditionally respond
        id: vars
        run: |
          echo "Current branch is: $env_branch"
          if [[ "$env_branch" == *"master"* ]]; then
            echo "$env_branch"
            echo "branch_folder="master-folder" >> $GITHUB_ENV
            
          else
            echo "This is not master branch"
            echo "branch_folder="dev-folder" >> $GITHUB_ENV
          fi
      - name: Print branch folder
        run: |
          echo "Branch folder is: $branch_folder"
